[env:esp32dev]

board = esp32dev
framework = arduino
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 115200
upload_resetmethod = nodemcu
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
lib_ldf_mode = chain+
platform = espressif32@6.9.0


build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DESP32
    -std=gnu++17
    -Wno-error=delete-non-virtual-dtor
    -Wno-error
    -fno-exceptions
    -DESP32
    

build_unflags = -frtti

build_src_flags =
    -fno-rtti

lib_deps =
    jrowberg/I2Cdevlib-MPU6050@^1.0.0
    
    mikalhart/TinyGPSPlus@^1.0.3
    https://github.com/tanakamasayuki/Arduino_TensorFlowLite_ESP32.git
    adafruit/RTClib@^2.1.4
    adafruit/Adafruit BusIO@^1.14.1
  
